# Main settings includes
include	mk/settings.mk

# Individual project settings (Optional)
#BOOT		= new
#APP		= 1
SPI_SPEED	= 40
SPI_MODE	= QIO
SPI_SIZE_MAP	= 4
ESPPORT		= COM19
ESPBAUD		= 320400

# Basic project settings
MODULES	= driver user
LIBS	= c gcc hal phy pp net80211 lwip wpa main crypto

# Root includes
include	mk/common_nonos.mk
